server:
  port: 8084

spring:
  application:
    name: ai-adapter
  flyway:
    schemas: public
    validate-on-migrate: false
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/ai-adapter-db
    driver-class-name: org.postgresql.Driver
    maximumPoolSize: 10
    minimumIdle: 5
    idleTimeout: 10000

integration:
  http:
    open-ai:
      base-url: https://api.openai.com/
      assistant: v1/assistants
      chat-url: v1/chat/completions
      speech-to-text: v1/audio/transcriptions
      text-to-speech: v1/audio/speech
      api-key: 1
      models:
        assistant: gpt-4-turbo
        text-to-speech: whisper-1
        speech-to-text: tts-1
    telegram:
      bot:
        username: Pythagoras_math_bot
        token: 1
        url: https://2d02-2603-8080-e5f0-94d0-89ec-fcb8-8a56-588c.ngrok-free.app
        path: /update
    retry:
      max-attempts: 3
      duration: 20
  mqtt:
    url: tcp://192.168.86.184:1883

logging:
  pattern:
    console: "%clr(%-5level) %d{yyy-MM-dd HH:mm:ss.SS} [%thread] %clr([%logger{0}.%M]){cyan} requestId:[%X{requestId}] %m%wEx%n"
    file: "[%-5level] %d{yyy-MM-dd HH:mm:ss.SS} [%thread] [%-26logger{26}] requestId:[%X{requestId}] %m%wEx%n"
  level:
    com:
      dmitrenko: debug